### ISSUE TITLE
Support compiling many files into one?

### ISSUE THREAD

**Issue by abelnation** [babel/grunt-babel#25] opened 2015-03-12 00:13 UTC
Is it only possible to compile single files to single files?  It's unclear if this is possible, e.g.

```
    babel: {
        options: {
            sourceMap: true,
        },
        src: {
            files: {
                './static/js/main.js': [
                    './static/es6/**/*.{es6,js6,jsx}',
                    './static/es6/*.{es6,js6,jsx}'
                ]
            }
        },
    };
```

**Comment by sindresorhus** [comment] 2015-03-12 05:38
Duplicate of https://github.com/babel/grunt-babel/pull/16

**Closed by sindresorhus** 2015-03-12 05:38 UTC
